# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Conquer Bulgaria Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Adding application configuration
        run: |
          printf ${{ secrets.APPLICATION_YML }} >> src/main/resources/application.yml
        shell: bash

      - name: Download firebase configuration
        uses: wei/wget@v1
        with:
          args: --no-check-certificate 'https://docs.google.com/uc?export=download&id=${{ secrets.FIREBASE_CONFIG_ID }}' -O src/main/resources/config.7z

      - name: Unarchive configuration
        uses: edgarrc/action-7z@v1
        with:
          args: 7z x src/main/resources/config.7z -p${{ secrets.FIREBASE_CONFIG_PASSWORD }}

      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: aezakme/conquer-bulgaria-deploy
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
